/* eslint-disable @next/next/no-img-element */

import { MinorHeader } from "~/components/minor-header";
import { PageHeader } from "~/components/page-header";
import { Paragraph } from "~/components/paragraph";
import { SectionHeader } from "~/components/section-header";

const HistoryPage = () => {
  return (
    <>
      <PageHeader>U.S. History and Context</PageHeader>

      <section>
        <SectionHeader>Barbering in America (1600s-1860s)</SectionHeader>

        <Paragraph>
          Barbering became a way for enslaved black men to navigate the world
          outside of plantations as skilled tradesmen. Many of these men became
          apprenticed to free Black men who had their own shops, or even set up
          their own shops with the slaveholder&apos;s permission. Most of the
          income generated by their services would be sent back to the
          slaveholder as a part of the condition of slavery.
        </Paragraph>
        <Paragraph>
          Being away from the plantation gave these men a type of mobility not
          found among many other enslaved people. Some could save a bit of the
          profits, and create opportunities to escape since they were not under
          the watch of the plantation owners, overseers, and other enslaved
          people.
        </Paragraph>

        <Paragraph>
          So the unique position of Black barbers was a kind of bridge between
          worlds. Free Black men who hired enslaved men entered a position of
          power: an employer, largely reserved as a luxury of whiteness and
          wealth. Simultaneously, those enslaved men who became appetences
          entered into the role of employee: a position vastly different from
          their forced position as property. This role of course is not like
          what we think of today in the employer/employee relationship. But it
          set the stage for what would continue to be a unique role for Black
          barber shops throughout their history.
        </Paragraph>

        <Paragraph>
          From its inception, the barbershop served as a place for congregation
          and discussion. In the beginning most clients were white men, but as
          time went on, the Black barbershop became one of the few spaces where
          several different brackets of men congregated across className and
          status, allowing for the unique position of the spaces to take shape.
        </Paragraph>
      </section>

      <section>
        <SectionHeader>Barbering in America (1860s-1890s)</SectionHeader>

        <Paragraph>
          With the end of the era of slavery in 1865, newly freed African
          Americans were still considered the lowest className. But this did not
          stop Black citizens from seeking a new beginning. African American
          historian Nell Painter, a professor at Princeton university, has
          tracked the millions of freed Blacks leaving the south at this time,
          and notes that the destinations were a lot more varied than we think.
          There was even a migration to Los Angeles, risking it all for rumors
          of a better life on the west coast. “That&apos;s action. That&apos;s
          taking your life in your hands,” said Painter. “That&apos;s the very
          definition of agency.” Black barbershops from the 1860s through the
          1890s were still almost exclusively serving white men. But that was
          soon to change.
        </Paragraph>

        <div className="flex w-full flex-col gap-4 py-4 lg:flex-row">
          <img src="/img/history-2.png" alt="" className="w-1/3 rounded" />
          <img src="/img/history-3.png" alt="" className="w-1/3 rounded" />
          <img src="/img/history-4.png" alt="" className="w-1/3 rounded" />
        </div>
      </section>

      <section>
        <SectionHeader>Barbering in America (1900s - 2020s)</SectionHeader>

        <Paragraph>
          The Black barbershop grew out of a place of servitude but eventually
          became a place of resistance, education, and emancipation. This
          continues today. First, they serve as a place for Black wealth
          generation through consistent patronage. Barbers develop relationships
          with their clientele and the communities they serve. Revenue
          generation depends on several characteristics such as reputation,
          quality, and connection. Barbering is a skilled profession, but one
          that has a lower barrier for entry than some others.
        </Paragraph>

        <div className="flex w-full flex-col gap-4 py-4 lg:flex-row ">
          <div className="w-1/4">
            <img
              src="/img/durham.jpg"
              alt=""
              className="aspect-[3/4] rounded"
            />
            <p className="text-muted-foreground !mt-2 text-sm">
              John Merrick from Durham, NC.
            </p>
            <p className="text-muted-foreground !mt-2 text-sm">
              Expanded from a barber shop to North Carolina&apos;s first
              Black-owned bank, drug store and other enterprises.
            </p>
            <p className="text-muted-foreground !mt-2 text-sm">
              Founded the NC Mutual Insurance Company.
            </p>
          </div>
          <div className="w-1/4">
            <img
              src="/img/herndon.jpg"
              alt=""
              className="aspect-[3/4]  rounded"
            />
            <p className="text-muted-foreground !mt-2 text-sm">
              Alonzo Herndon from Atlanta, GA.
            </p>
            <p className="text-muted-foreground !mt-2 text-sm">
              Niagara Movement
            </p>
            <p className="text-muted-foreground !mt-2 text-sm">
              ATL Life Insurance Company
            </p>
            <p className="text-muted-foreground !mt-2 text-sm">
              One of the first Black Millionaires.
            </p>
          </div>
        </div>
        <Paragraph>
          Barber shops joined black churches, beauty shops and the Black press
          as a space for the public sphere of Black life. A place where Black
          citizens across classNamees and backgrounds engaged in lively
          discourse about political and daily events. Black men have
          historically had few spaces where they can congregate freely and
          deliberately, with privacy to discuss issues important to them.
          Barbershops have served as spaces for vulnerability and bravado; for
          honoring tradition and admiring innovation. Films that capture the
          essence of these spaces include
          <em>Coming to America</em>
          (1988),
          <em>Malcolm X</em> (1992), and
          <em>Barbershop</em> (2002). Notable authors such as Ralph Ellison,
          Toni Morrison, Amiri Bakara and Richard Wright also pay homage to the
          importance of the barbershop to Black men in America.
        </Paragraph>
        <div className="flex w-full flex-col gap-4 py-4 lg:flex-row ">
          <img
            src="/img/coming-to-america.png"
            alt=""
            className="w-1/4 rounded"
          />

          <img src="/img/barbershop.png" alt="" className="w-1/4 rounded" />

          <img src="/img/malcom-x.png" alt="" className="w-1/4 rounded" />
        </div>

        <MinorHeader>Example</MinorHeader>

        <video controls width="100%" className="mx-auto mb-4" id="historyVid">
          <source src="/video/morgan.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <Paragraph className="text-muted-foreground text-sm">
          Henry Miller Morgan: Founder of Tyler Barber College, the first
          barbering school for African Americans in Tyler,Texas, USA. At one
          time, approximately 80% of all African American Barbers were educated
          at this school.
        </Paragraph>
      </section>
    </>
  );
};

export default HistoryPage;
