import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { NavBar } from "~/components/navbar";
import { SideNav } from "~/components/sidenav";
import { ScrollArea } from "~/components/ui/scroll-area";
import { barbershopConfig } from "~/data/barbershop";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} h-svh`}>
        <div className="border-b">
          {" "}
          <NavBar />
          <div className="container flex-1 items-start pt-24 md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">
            <aside className="fixed top-16 z-30 -ml-2 hidden h-[calc(100vh-3.5rem)] w-full shrink-0 md:sticky md:block">
              <SideNav config={barbershopConfig} />
            </aside>
            <main className="p-4">{children}</main>
          </div>
        </div>

        {/* <main className="mx-auto  flex  h-full w-full max-w-7xl p-4 pt-8">
          <SideNav config={barbershopConfig} />
          <section>{children}</section>
        </main> */}
      </body>
    </html>
  );
}
